'''
Created on 27 nov. 2014

@author: Pieter
'''
lesroosters = [{
                'naam':u'Practicumuren',
                0:{
                   1:{"klas":u"1G","lokaal":u"306"},
                   2:{"klas":u"3D","lokaal":u"306"},
                   3:{"klas":u".","lokaal":u""},
                   4:{"klas":u".","lokaal":u""},
                   5:{"klas":u"2B","lokaal":u"306"},
                   6:{"klas":u".","lokaal":u""},
                   7:{"klas":u"2F","lokaal":u"306"},
                   8:{"klas":u".","lokaal":u""}
                   },
                1:{
                   1:{"klas":u"1F","lokaal":u"306"},
                   2:{"klas":u"3F","lokaal":u"306"},
                   3:{"klas":u"2E","lokaal":u"306"},
                   4:{"klas":u".","lokaal":u""},
                   5:{"klas":u"2G","lokaal":u"306"},
                   6:{"klas":u"2C","lokaal":u"306"},
                   7:{"klas":u"1D","lokaal":u"306"},
                   8:{"klas":u".","lokaal":u""}
                   },
                2:{
                   1:{"klas":u"1A","lokaal":u"306"},
                   2:{"klas":u"3B","lokaal":u"310"},
                   3:{"klas":u"1B","lokaal":u"306"},
                   4:{"klas":u".","lokaal":u""},
                   5:{"klas":u"1H","lokaal":u"306"},
                   6:{"klas":u".","lokaal":u""},
                   7:{"klas":u".","lokaal":u""},
                   8:{"klas":u".","lokaal":u""}
                   },
                3:{
                   1:{"klas":u"3E","lokaal":u"306"},
                   2:{"klas":u"3G","lokaal":u"306"},
                   3:{"klas":u"2A","lokaal":u"306"},
                   4:{"klas":u"3H","lokaal":u"306"},
                   5:{"klas":u".","lokaal":u""},
                   6:{"klas":u".","lokaal":u""},
                   7:{"klas":u".","lokaal":u""},
                   8:{"klas":u".","lokaal":u""}
                   },
                4:{
                   1:{"klas":u"3A","lokaal":u"306"},
                   2:{"klas":u"3C","lokaal":u"306"},
                   3:{"klas":u".","lokaal":u""},
                   4:{"klas":u"1E","lokaal":u"306"},
                   5:{"klas":u"1D","lokaal":u"306"},
                   6:{"klas":u"1C","lokaal":u"306"},
                   7:{"klas":u".","lokaal":u""},
                   8:{"klas":u".","lokaal":u""}
                   },
                'vak':u"NA"
                },
               {
                'naam':u'Kamphorst',
                0:{
                   1:{"klas":u"3E","lokaal":u"310"},
                   2:{"klas":u"3F","lokaal":u"310"},
                   3:{"klas":u".","lokaal":u""},
                   4:{"klas":u"54","lokaal":u"310"},
                   5:{"klas":u"44","lokaal":u"310"},
                   6:{"klas":u"43","lokaal":u"306"},
                   7:{"klas":u"2F","lokaal":u"306"},
                   8:{"klas":u".","lokaal":u""}
                   },
                1:{
                   1:{"klas":u"3B","lokaal":u"105"},
                   2:{"klas":u"3F","lokaal":u"306"},
                   3:{"klas":u"2E","lokaal":u"306"},
                   4:{"klas":u".","lokaal":u""},
                   5:{"klas":u".","lokaal":u""},
                   6:{"klas":u".","lokaal":u""},
                   7:{"klas":u".","lokaal":u""},
                   8:{"klas":u".","lokaal":u""}
                   },
                2:{
                   1:{"klas":u"44","lokaal":u"310"},
                   2:{"klas":u"3B","lokaal":u"310"},
                   3:{"klas":u"3F","lokaal":u"310"},
                   4:{"klas":u"3E","lokaal":u"310"},
                   5:{"klas":u"612","lokaal":u"310"},
                   6:{"klas":u".","lokaal":u""},
                   7:{"klas":u".","lokaal":u""},
                   8:{"klas":u".","lokaal":u""}
                   },
                3:{
                   1:{"klas":u"3E","lokaal":u"306"},
                   2:{"klas":u".","lokaal":u""},
                   3:{"klas":u"54","lokaal":u"309"},
                   4:{"klas":u"54","lokaal":u"309"},
                   5:{"klas":u".","lokaal":u""},
                   6:{"klas":u".","lokaal":u""},
                   7:{"klas":u".","lokaal":u""},
                   8:{"klas":u".","lokaal":u""}
                   },
                4:{
                   1:{"klas":u"612","lokaal":u"310"},
                   2:{"klas":u"612","lokaal":u"310"},
                   3:{"klas":u".","lokaal":u""},
                   4:{"klas":u"2E","lokaal":u"310"},
                   5:{"klas":u".","lokaal":u""},
                   6:{"klas":u"43","lokaal":u"310"},
                   7:{"klas":u".","lokaal":u""},
                   8:{"klas":u".","lokaal":u""}
                   },
                'vak':u"NA"
                }]