'''
Created on 27 nov. 2014

@author: Pieter
'''
lesroosters = [{
                'naam':u'Practicumuren Natuurkunde',
                0:{
                   1:{"vak":u"NA","klas":u"1G","lokaal":u"306"},
                   2:{"vak":u"NA","klas":u"3D","lokaal":u"306"},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"NA","klas":u"2B","lokaal":u"306"},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"NA","klas":u"2F","lokaal":u"306"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                1:{
                   1:{"vak":u"NA","klas":u"1F","lokaal":u"306"},
                   2:{"vak":u"NA","klas":u"3F","lokaal":u"306"},
                   3:{"vak":u"NA","klas":u"2E","lokaal":u"306"},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"NA","klas":u"2G","lokaal":u"306"},
                   6:{"vak":u"NA","klas":u"2C","lokaal":u"306"},
                   7:{"vak":u"NA","klas":u"2D","lokaal":u"306"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                2:{
                   1:{"vak":u"NA","klas":u"1A","lokaal":u"306"},
                   2:{"vak":u"NA","klas":u"3B","lokaal":u"310"},
                   3:{"vak":u"NA","klas":u"1B","lokaal":u"306"},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"NA","klas":u"1H","lokaal":u"306"},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                3:{
                   1:{"vak":u"NA","klas":u"3E","lokaal":u"306"},
                   2:{"vak":u"NA","klas":u"3G","lokaal":u"306"},
                   3:{"vak":u"NA","klas":u"2A","lokaal":u"306"},
                   4:{"vak":u"NA","klas":u"3H","lokaal":u"306"},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                4:{
                   1:{"vak":u"NA","klas":u"3A","lokaal":u"306"},
                   2:{"vak":u"NA","klas":u"3C","lokaal":u"306"},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"NA","klas":u"1E","lokaal":u"306"},
                   5:{"vak":u"NA","klas":u"1D","lokaal":u"306"},
                   6:{"vak":u"NA","klas":u"1C","lokaal":u"306"},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   }
                },
               {
                'naam':u'Practicumuren Biologie',
                0:{
                   1:{"vak":u"BI","klas":u"1E","lokaal":u"300"},
                   2:{"vak":u"BI","klas":u"1E","lokaal":u"300"},
                   3:{"vak":u"BI","klas":u"1B","lokaal":u"300"},
                   4:{"vak":u"BI","klas":u"1B","lokaal":u"300"},
                   5:{"vak":u"BI","klas":u"512","lokaal":u"300"},
                   6:{"vak":u"BI","klas":u"2A","lokaal":u"300"},
                   7:{"vak":u"BI","klas":u"2C","lokaal":u"300"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                1:{
                   1:{"vak":u"BI","klas":u"511","lokaal":u"300"},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"BI","klas":u"41","lokaal":u"300"},
                   4:{"vak":u"BI","klas":u"1A","lokaal":u"300"},
                   5:{"vak":u"BI","klas":u"1A","lokaal":u"300"},
                   6:{"vak":u"BI","klas":u"1H","lokaal":u"300"},
                   7:{"vak":u"BI","klas":u"1H","lokaal":u"300"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                2:{
                   1:{"vak":u"BI","klas":u"44","lokaal":u"300"},
                   2:{"vak":u"BI","klas":u"2G","lokaal":u"300"},
                   3:{"vak":u"BI","klas":u"2E","lokaal":u"300"},
                   4:{"vak":u"BI","klas":u"1G","lokaal":u"300"},
                   5:{"vak":u"BI","klas":u"1G","lokaal":u"300"},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                3:{
                   1:{"vak":u"BI","klas":u"1C","lokaal":u"300"},
                   2:{"vak":u"BI","klas":u"1C","lokaal":u"300"},
                   3:{"vak":u"BI","klas":u"2B","lokaal":u"300"},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"BI","klas":u"2D","lokaal":u"300"},
                   6:{"vak":u"BI","klas":u"2F","lokaal":u"300"},
                   7:{"vak":u"BI","klas":u"59","lokaal":u"300"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                4:{
                   1:{"vak":u"BI","klas":u"1D","lokaal":u"300"},
                   2:{"vak":u"BI","klas":u"1D","lokaal":u"300"},
                   3:{"vak":u"BI","klas":u"1F","lokaal":u"300"},
                   4:{"vak":u"BI","klas":u"1F","lokaal":u"300"},
                   5:{"vak":u"BI","klas":u"42","lokaal":u"300"},
                   6:{"vak":u"BI","klas":u"43","lokaal":u"300"},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   }
                },
               {
                'naam':u'Practicumuren Scheikunde',
                0:{
                   1:{"vak":u"SK","klas":u"3B","lokaal":u"302"},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"SK","klas":u"43","lokaal":u"302"},
                   7:{"vak":u"SK","klas":u"3E","lokaal":u"302"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                1:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"SK","klas":u"3G","lokaal":u"302"},
                   3:{"vak":u"SK","klas":u"3A","lokaal":u"302"},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"SK","klas":u"3D","lokaal":u"302"},
                   7:{"vak":u"SK","klas":u"3H","lokaal":u"302"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                2:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"SK","klas":u"54","lokaal":u"302"},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                3:{
                   1:{"vak":u"SK","klas":u"3F","lokaal":u"302"},
                   2:{"vak":u"SK","klas":u"48","lokaal":u"302"},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"SK","klas":u"54","lokaal":u"302"},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"SK","klas":u"57","lokaal":u"302"},
                   7:{"vak":u"SK","klas":u"59","lokaal":u"302"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                4:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"SK","klas":u"41","lokaal":u"302"},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"SK","klas":u"3C","lokaal":u"302"},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   }
                },
               {
                'naam':u'Kamphorst',
                0:{
                   1:{"vak":u"NA","klas":u"3E","lokaal":u"310"},
                   2:{"vak":u"NA","klas":u"3F","lokaal":u"310"},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"NA","klas":u"54","lokaal":u"310"},
                   5:{"vak":u"NA","klas":u"44","lokaal":u"310"},
                   6:{"vak":u"NA","klas":u"43","lokaal":u"306"},
                   7:{"vak":u"NA","klas":u"2F","lokaal":u"306"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                1:{
                   1:{"vak":u"NA","klas":u"3B","lokaal":u"105"},
                   2:{"vak":u"NA","klas":u"3F","lokaal":u"306"},
                   3:{"vak":u"NA","klas":u"2E","lokaal":u"306"},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                2:{
                   1:{"vak":u"NA","klas":u"44","lokaal":u"310"},
                   2:{"vak":u"NA","klas":u"3B","lokaal":u"310"},
                   3:{"vak":u"NA","klas":u"3F","lokaal":u"310"},
                   4:{"vak":u"NA","klas":u"3E","lokaal":u"310"},
                   5:{"vak":u"NA","klas":u"612","lokaal":u"310"},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                3:{
                   1:{"vak":u"NA","klas":u"3E","lokaal":u"306"},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"NA","klas":u"54","lokaal":u"309"},
                   4:{"vak":u"NA","klas":u"54","lokaal":u"309"},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                4:{
                   1:{"vak":u"NA","klas":u"612","lokaal":u"310"},
                   2:{"vak":u"NA","klas":u"612","lokaal":u"310"},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"NA","klas":u"2E","lokaal":u"310"},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"NA","klas":u"43","lokaal":u"310"},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   }
                },
               {
                'naam':u'Burggraaf',
                0:{
                   1:{"vak":u"NA","klas":u"53","lokaal":u"309"},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"NA","klas":u"63","lokaal":u"309"},
                   4:{"vak":u"NA","klas":u"65","lokaal":u"309"},
                   5:{"vak":u"NA","klas":u"1F","lokaal":u"B06"},
                   6:{"vak":u"NA","klas":u"1H","lokaal":u"B06"},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                1:{
                   1:{"vak":u"NA","klas":u"1F","lokaal":u"306"},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"NA","klas":u"65","lokaal":u"309"},
                   4:{"vak":u"NA","klas":u"53","lokaal":u"308"},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"NA","klas":u"45","lokaal":u"308"},
                   8:{"vak":u"NA","klas":u"63","lokaal":u"308"}
                   },
                2:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"NA","klas":u"45","lokaal":u"309"},
                   3:{"vak":u"NA","klas":u"63","lokaal":u"309"},
                   4:{"vak":u"NA","klas":u"53","lokaal":u"306"},
                   5:{"vak":u"NA","klas":u"1H","lokaal":u"306"},
                   6:{"vak":u"NA","klas":u"65","lokaal":u"306"},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                3:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                4:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   }
                 },
               {
                'naam':u'Beekman',
                0:{
                   1:{"vak":u"","klas":u",","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"NA","klas":u"48","lokaal":u"310"},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"NA","klas":u"3H","lokaal":u"309"},
                   6:{"vak":u"NA","klas":u"56","lokaal":u"310"},
                   7:{"vak":u"NA","klas":u"56","lokaal":u"310"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                1:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                2:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                3:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"NA","klas":u"48","lokaal":u"308"},
                   3:{"vak":u"NA","klas":u"3H","lokaal":u"110"},
                   4:{"vak":u"NA","klas":u"3H","lokaal":u"306"},
                   5:{"vak":u"NA","klas":u"56","lokaal":u"306"},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                4:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   }
                 },
               {
                'naam':u'Snelders',
                0:{
                   1:{"vak":u"NA","klas":u"1G","lokaal":u"306"},
                   2:{"vak":u"NA","klas":u"3D","lokaal":u"306"},
                   3:{"vak":u"NA","klas":u"1E","lokaal":u"B12"},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"NA","klas":u"2B","lokaal":u"306"},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                1:{
                   1:{"vak":u"NA","klas":u"1G","lokaal":u"302"},
                   2:{"vak":u"SK","klas":u"3G","lokaal":u"302"},
                   3:{"vak":u"SK","klas":u"41","lokaal":u"111"},
                   4:{"vak":u"NA","klas":u"3D","lokaal":u"302"},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                2:{
                   1:{"vak":u"NA","klas":u"1A","lokaal":u"308"},
                   2:{"vak":u"SK","klas":u"45","lokaal":u"302"},
                   3:{"vak":u"NA","klas":u"3G","lokaal":u"308"},
                   4:{"vak":u"NA","klas":u"3D","lokaal":u"308"},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                3:{
                   1:{"vak":u"SK","klas":u"45","lokaal":u"308"},
                   2:{"vak":u"NA","klas":u"3G","lokaal":u"306"},
                   3:{"vak":u"NA","klas":u"2A","lokaal":u"306"},
                   4:{"vak":u"SK","klas":u"3G","lokaal":u"300"},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                4:{
                   1:{"vak":u"NA","klas":u"2B","lokaal":u"308"},
                   2:{"vak":u"NA","klas":u"3G","lokaal":u"308"},
                   3:{"vak":u"Sk","klas":u"41","lokaal":u"302"},
                   4:{"vak":u"NA","klas":u"1E","lokaal":u"306"},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   }
                },
               {
                'naam':u'Van Praagh',
                0:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"NA","klas":u"3C","lokaal":u"202"},
                   3:{"vak":u"NA","klas":u"3A","lokaal":u"306"},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"NA","klas":u"1C","lokaal":u"B13"},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"NA","klas":u"2D","lokaal":u"309"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                1:{
                   1:{"vak":u"NA","klas":u"3C","lokaal":u"310"},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"NA","klas":u"1D","lokaal":u"B02"},
                   4:{"vak":u"na","klas":u"3A","lokaal":u"306"},
                   5:{"vak":u"NA","klas":u"2G","lokaal":u"306"},
                   6:{"vak":u"NA","klas":u"2C","lokaal":u"306"},
                   7:{"vak":u"NA","klas":u"2D","lokaal":u"306"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                2:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                3:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                4:{
                   1:{"vak":u"NA","klas":u"3A","lokaal":u"306"},
                   2:{"vak":u"NA","klas":u"3C","lokaal":u"306"},
                   3:{"vak":u"NA","klas":u"2G","lokaal":u"308"},
                   4:{"vak":u"NA","klas":u"2C","lokaal":u"308"},
                   5:{"vak":u"NA","klas":u"1D","lokaal":u"306"},
                   6:{"vak":u"NA","klas":u"1C","lokaal":u"306"},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   }
                },
               {
                'naam':u'Van Der Sluis',
                0:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"MLES","klas":u"1B","lokaal":u"B15"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                1:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"WIB","klas":u"69","lokaal":u"310"},
                   7:{"vak":u"WIB","klas":u"69","lokaal":u"310"},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                2:{
                   1:{"vak":u"NA","klas":u"1A","lokaal":u"306"},
                   2:{"vak":u"WIB","klas":u"609","lokaal":u"306"},
                   3:{"vak":u"NA","klas":u"1B","lokaal":u"306"},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"NLT","klas":u"66","lokaal":u"306"},
                   8:{"vak":u"NLT","klas":u"66","lokaal":u"306"}
                   },
                3:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"","klas":u".","lokaal":u""},
                   4:{"vak":u"","klas":u".","lokaal":u""},
                   5:{"vak":u"","klas":u".","lokaal":u""},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   },
                4:{
                   1:{"vak":u"","klas":u".","lokaal":u""},
                   2:{"vak":u"","klas":u".","lokaal":u""},
                   3:{"vak":u"NA","klas":u"1B","lokaal":u"B13"},
                   4:{"vak":u"WIB","klas":u"69","lokaal":u"B13"},
                   5:{"vak":u"NA","klas":u"1A","lokaal":u"B13"},
                   6:{"vak":u"","klas":u".","lokaal":u""},
                   7:{"vak":u"","klas":u".","lokaal":u""},
                   8:{"vak":u"","klas":u".","lokaal":u""}
                   }
                }]